// src/components/FloorsContainer.svelte
<script lang="ts">
    import Floor from './Floor.svelte'
    import type { Floor as FloorType } from '../interfaces/floor'

    const { className, current, duration, floors, hasStarted, lightColors } = $props()

    const reversedFloors = $derived(
        floors
            .map((floor: FloorType, index: number) => ({ floor, index }))
            .reverse()
    )
</script>

<div class={className}>
    <div class="border-l border-slate-400 border-t flex-grow grid max-x-auto max-w min-h-full">
        {#each reversedFloors as item (item.floor.id)}
            <Floor
                active={current === Number(item.floor.id)}
                {duration}
                {hasStarted}
                label={item.floor.label}
                light={lightColors[item.index]}
            />
        {/each}
    </div>
</div>

// src/components/floors-container.tsx
import { FloorComponent } from '.';
import { Floor } from '../interfaces';

interface Props {
  className: string;
  current: number;
  duration: number;
  floors: Floor[];
  hasStarted: boolean;
  lightColors: string[];
}

export const FloorsContainerComponent = ({ className, current, duration, floors, hasStarted, lightColors }: Props)  => {
  return (
    <div className={ className }>
      <div className="border-l border-slate-400 border-t flex-grow grid max-x-auto max-w min-h-full">
        {
          floors.map(({ id, label }, index) => (
            <FloorComponent
              active={ current === Number(id) }
              duration={ duration }
              hasStarted={ hasStarted }
              key={ id }
              label={ label }
              light={ lightColors[index] }
            />
          )).reverse()
        }
      </div>
    </div>
  );
}
